name: mypod_flutter
description: A new Flutter project with Supabase.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  
  path_provider: ^2.1.5
  camera: ^0.11.1
  gal: ^2.3.1
  google_sign_in: ^6.2.2
  confetti: ^0.8.0
  audioplayers: ^6.4.0
  video_player: ^2.8.2

  supabase_flutter: ^2.8.4
  flutter_facebook_auth: ^7.1.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_blurhash: ^0.8.2
  flutter_riverpod: ^2.6.1
  provider: ^6.1.4
  logging: ^1.3.0



dev_dependencies:
  flutter_lints: '>=3.0.0 <6.0.0'
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3  
  photo_view: ^0.15.0
  build_runner: ^2.4.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
   - assets/images/rank1.jpg
   - assets/images/bg.jpg
   - assets/sounds/correct.mp3
   - assets/sounds/wrong.mp3
   - assets/alphabet_images/a.jpg
   - assets/alphabet_images/b.jpg
   - assets/alphabet_images/c.jpg
   - assets/alphabet_images/d.jpg
   - assets/alphabet_images/e.jpg
   - assets/alphabet_images/f.jpg
   - assets/alphabet_images/g.jpg
   - assets/alphabet_images/h.jpg
   - assets/alphabet_images/i.jpg
   - assets/alphabet_images/j.jpg
   - assets/alphabet_images/k.jpg
   - assets/alphabet_images/l.jpg
   - assets/alphabet_images/m.jpg
   - assets/alphabet_images/n.jpg
   - assets/alphabet_images/o.jpg
   - assets/alphabet_images/p.jpg
   - assets/alphabet_images/q.jpg
   - assets/alphabet_images/r.jpg
   - assets/alphabet_images/s.jpg
   - assets/alphabet_images/t.jpg
   - assets/alphabet_images/u.jpg
   - assets/alphabet_images/v.jpg
   - assets/alphabet_images/w.jpg
   - assets/alphabet_images/x.jpg
   - assets/alphabet_images/y.jpg
   - assets/alphabet_images/z.jpg
   - assets/images/practice_background.png
   - assets/images/close_icon.png
   - assets/images/scenario_image.png
   - assets/images/camera_icon.png
   - assets/images/login_background.png
   - assets/images/profile_picture.jpg
   - assets/images/unit1.jpg
   - assets/images/unit2.jpg
   - assets/images/unit3.jpg
   - assets/images/unit4.jpg
   - assets/images/unit5.jpg
   - assets/images/unit6.jpg
   - assets/images/unit7.jpg
   - assets/images/unit8.jpg
   - assets/images/unit9.jpg
   - assets/images/unit10.jpg
   - assets/images/forgot_password.gif
   - assets/images/signup_bg.jpg
   - assets/images/avatar.gif
   - assets/images/banner.png
   - assets/images/developer1.jpg
   - assets/images/developer2.jpg
   - assets/images/developer3.jpg
   - assets/images/splash_bg.png
   - assets/icons/home_icon.png
   - assets/icons/asl_alphabet_icon.png
   - assets/icons/practice_icon.png
   - assets/icons/leaderboard_icon.png
   - assets/icons/profile_icon.png
   - assets/icons/chest.png
   - assets/icons/notification_icon.jpg
   - assets/icons/google_logo.png
   - assets/icons/fb_logo.png
   - assets/rewards/sticker1.jpg
   - assets/rewards/sticker2.jpg
   - assets/rewards/sticker3.jpg
   - assets/rewards/sticker4.jpg
   - assets/rewards/sticker5.jpg
   - assets/rewards/sticker6.jpg
   - assets/rewards/sticker7.jpg
   - assets/rewards/sticker8.jpg
   - assets/rewards/sticker9.jpg
   - assets/rewards/sticker10.jpg
   - assets/sounds/confetti.mp3
   - assets/avatars/avatar1.png
   - assets/avatars/avatar2.png
   - assets/avatars/avatar3.png
   - assets/avatars/avatar4.png
   - assets/avatars/avatar5.png
   - assets/avatars/avatar6.png
   - assets/images/International_Symbol_for _Deafness.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
